import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Rubik } from "next/font/google";
import LenisSmoothScrollProps from "@/components/lenisScroll";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const rubik = Rubik({ subsets: ["latin"], variable: "--font-rubik" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            {/* `${inter.variable} ${rubik.variable}` */}
            <body className={rubik.className}>
                <LenisSmoothScrollProps>{children}</LenisSmoothScrollProps>
            </body>
        </html>
    );
}
